name: V / Advisory (latest V)

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  advisory:
    name: Advisory only - latest V on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, windows-2022, macOS-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Vlang
        uses: vlang/setup-v@663cc08827d1fc0532ee755b4dedbb183c11d06a # v1.7

      - name: Run tests for all exercises
        shell: bash
        run: bin/test
